mlp:
  nonlinearity: null
  layer_type: "continuous"
  n: 2
  n_in: null
  n_out: null
  n_hidden: null
  periodicity: 2.0
  rescale_output: False
  scale: 2.0
  normalize: False # TODO: Not working when True with the jacobian calculation
  segments: 4
  input:
    segments: ${mlp.segments}
    width: 2
  output:
    segments: ${mlp.segments}
    width: 3
  hidden:
    segments: ${mlp.segments}
    layers: 3
    width: 60

# generate this many interior data points
data_size: 10000

max_epochs: 100
gpus: 1
lr: 1e-3
batch_size: 128

# Are you training? Otherwise plot the result
train: True
checkpoint: null
rotations: 1 # NOT Implemented! 1 is x,y, 2 is x,y, x-y, x+y, greater includes additional rotations
save_images: True

defaults :
  - optimizer : adam